/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2018_09_03_aplicacionvisualalumnos;

import java.util.Random;

/**
 *
 * @author aa517
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextNombre1 = new javax.swing.JTextField();
        jTextTareas1 = new javax.swing.JTextField();
        jTextProyectos1 = new javax.swing.JTextField();
        jTextExamen1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCalificacion2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextNombre3 = new javax.swing.JTextField();
        jTextNombre2 = new javax.swing.JTextField();
        jTextTareas3 = new javax.swing.JTextField();
        jTextProyectos2 = new javax.swing.JTextField();
        jTextTareas2 = new javax.swing.JTextField();
        jTextProyectos3 = new javax.swing.JTextField();
        jTextExamen2 = new javax.swing.JTextField();
        jTextExamen3 = new javax.swing.JTextField();
        jLabelCalificacion1 = new javax.swing.JLabel();
        jLabelCalificacion3 = new javax.swing.JLabel();
        jLabelProyectosProm = new javax.swing.JLabel();
        jLabelTareasProm = new javax.swing.JLabel();
        jLabelExamenProm = new javax.swing.JLabel();
        jLabelCalificaciones = new javax.swing.JLabel();
        jButAleatorios = new javax.swing.JButton();
        jButCalcular = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jLabelMejor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alumno 1");

        jTextNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre1ActionPerformed(evt);
            }
        });

        jTextTareas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTareas1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Tareas");

        jLabel4.setText("Proyectos");

        jLabel5.setText("Examen");

        jLabel6.setText("Calificacion");

        jLabelCalificacion2.setBackground(new java.awt.Color(255, 102, 0));
        jLabelCalificacion2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCalificacion2.setOpaque(true);

        jLabel8.setText("Alumno 3");

        jLabel9.setText("Alumno 2");

        jTextNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre3ActionPerformed(evt);
            }
        });

        jTextNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre2ActionPerformed(evt);
            }
        });

        jTextTareas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTareas3ActionPerformed(evt);
            }
        });

        jTextProyectos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProyectos2ActionPerformed(evt);
            }
        });

        jTextTareas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTareas2ActionPerformed(evt);
            }
        });

        jTextProyectos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProyectos3ActionPerformed(evt);
            }
        });

        jTextExamen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExamen2ActionPerformed(evt);
            }
        });

        jTextExamen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExamen3ActionPerformed(evt);
            }
        });

        jLabelCalificacion1.setBackground(new java.awt.Color(255, 102, 0));
        jLabelCalificacion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCalificacion1.setOpaque(true);

        jLabelCalificacion3.setBackground(new java.awt.Color(255, 102, 0));
        jLabelCalificacion3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCalificacion3.setOpaque(true);

        jLabelProyectosProm.setBackground(new java.awt.Color(255, 102, 0));
        jLabelProyectosProm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelProyectosProm.setOpaque(true);

        jLabelTareasProm.setBackground(new java.awt.Color(255, 102, 0));
        jLabelTareasProm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTareasProm.setOpaque(true);

        jLabelExamenProm.setBackground(new java.awt.Color(255, 102, 0));
        jLabelExamenProm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelExamenProm.setOpaque(true);

        jLabelCalificaciones.setBackground(new java.awt.Color(153, 0, 0));
        jLabelCalificaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCalificaciones.setOpaque(true);

        jButAleatorios.setText("ALEATORIOS");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButCalcular.setText("CALCULAR");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButBorrar.setText("BORRAR");
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        jLabelMejor.setBackground(new java.awt.Color(255, 153, 153));
        jLabelMejor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMejor.setOpaque(true);

        jLabel7.setText("El mejor alumno es: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(145, 145, 145))
                            .addComponent(jButCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextTareas2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButAleatorios)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextTareas3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTareasProm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelProyectosProm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextProyectos1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextProyectos3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextProyectos2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelExamenProm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextExamen1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jTextExamen2)
                                    .addComponent(jTextExamen3))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCalificacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCalificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCalificacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMejor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextProyectos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jLabelCalificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTareas2)
                        .addComponent(jTextProyectos2)
                        .addComponent(jTextExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCalificacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextExamen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProyectos3)
                            .addComponent(jTextTareas3)
                            .addComponent(jTextNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelCalificacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelExamenProm, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelProyectosProm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTareasProm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabelMejor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel7)))
                        .addGap(68, 68, 68))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre1ActionPerformed

    private void jTextTareas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTareas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTareas1ActionPerformed

    private void jTextNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre3ActionPerformed

    private void jTextNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre2ActionPerformed

    private void jTextTareas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTareas3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTareas3ActionPerformed

    private void jTextProyectos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProyectos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProyectos2ActionPerformed

    private void jTextTareas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTareas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTareas2ActionPerformed

    private void jTextProyectos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProyectos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProyectos3ActionPerformed

    private void jTextExamen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExamen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExamen2ActionPerformed

    private void jTextExamen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExamen3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExamen3ActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        jTextTareas1.setText(30+azar.nextInt(71)+"");
        jTextTareas2.setText(30+azar.nextInt(71)+"");
        jTextTareas3.setText(30+azar.nextInt(71)+"");
        
        jTextProyectos1.setText(30+azar.nextInt(71)+"");
        jTextProyectos2.setText(30+azar.nextInt(71)+"");
        jTextProyectos3.setText(30+azar.nextInt(71)+"");
        
        jTextExamen1.setText(30+azar.nextInt(71)+"");
        jTextExamen2.setText(30+azar.nextInt(71)+"");
        jTextExamen3.setText(30+azar.nextInt(71)+"");
        
        String [] nombres = {"Juan","Maria","Pedro","Laura","Diana","Luis","Raul",
                             "Patricia","Fernanda","Jesus","Natalia","Jaime"};
        String [] apellidos = {"Piña","Perez","Pocholo","Azpilicueta"};
        
        jTextNombre1.setText(nombres[azar.nextInt(nombres.length)]+
                              apellidos[azar.nextInt(apellidos.length)]);
        jTextNombre2.setText(nombres[azar.nextInt(nombres.length)]+
                              apellidos[azar.nextInt(apellidos.length)]);
        jTextNombre3.setText(nombres[azar.nextInt(nombres.length)]+
                              apellidos[azar.nextInt(apellidos.length)]);
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        Alumno uno = new Alumno();
        
        uno.setNombre(jTextNombre1.getText());
        uno.setTareas(Integer.parseInt(jTextTareas1.getText()));
        uno.setProyectos(Integer.parseInt(jTextProyectos1.getText()));
        uno.setExamen(Integer.parseInt(jTextExamen1.getText()));
        
        Alumno dos = new Alumno(jTextNombre2.getText(),
                  Integer.parseInt(jTextTareas2.getText()),
                  Integer.parseInt(jTextProyectos2.getText()),
                  Integer.parseInt(jTextTareas2.getText()));
        
        String nom3= jTextNombre3.getText();
        int tar3=Integer.parseInt(jTextTareas3.getText());
        int proy3=Integer.parseInt(jTextProyectos3.getText());
        int exa3=Integer.parseInt(jTextProyectos3.getText());
        
        Alumno tres = new Alumno(nom3,tar3,proy3,exa3);
        jLabelCalificacion1.setText(uno.calcularCalificacion()+"");
        jLabelCalificacion2.setText(dos.calcularCalificacion()+"");
        jLabelCalificacion3.setText(tres.calcularCalificacion()+"");
        
        double promediogeneral=(uno.calcularCalificacion()+
                                dos.calcularCalificacion()+
                                tres.calcularCalificacion())/3;
        
        double promTareas=(uno.getTareas()+
                           dos.getTareas()+
                           tres.getTareas())/3;
        
        double promProyectos=(uno.getProyectos()+
                              dos.getProyectos()+
                              tres.getProyectos())/3;
        
        double promExamen=(uno.getExamen()+
                           dos.getExamen()+
                           tres.getExamen())/3;
        
        jLabelTareasProm.setText(promTareas+"");
        jLabelProyectosProm.setText(promProyectos+"");
        jLabelExamenProm.setText(promExamen+"");
        jLabelCalificaciones.setText(promediogeneral+"");
                               
        if(uno.calcularCalificacion()> dos.calcularCalificacion())
            if(uno.calcularCalificacion()>tres.calcularCalificacion())
                jLabelMejor.setText(uno.getNombre());
        else
                jLabelMejor.setText(dos.getNombre());
        if(dos.calcularCalificacion()>tres.calcularCalificacion())
            jLabelMejor.setText(dos.getNombre());
        else
            jLabelMejor.setText(tres.getNombre());
        
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
        jTextNombre1.setText("");
        jTextNombre2.setText("");
        jTextNombre3.setText("");
        
        jTextTareas1.setText("");
        jTextTareas2.setText("");
        jTextTareas3.setText("");
        
        jTextProyectos1.setText("");
        jTextProyectos2.setText("");
        jTextProyectos3.setText("");
        
        jTextExamen1.setText("");
        jTextExamen2.setText("");
        jTextExamen3.setText("");
        
        jLabelCalificaciones.setText("");
        
        jLabelCalificacion1.setText("");
        jLabelCalificacion2.setText("");
        jLabelCalificacion3.setText("");
        
        jLabelTareasProm.setText("");
        jLabelProyectosProm.setText("");
        jLabelExamenProm.setText("");
    }//GEN-LAST:event_jButBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCalificacion1;
    private javax.swing.JLabel jLabelCalificacion2;
    private javax.swing.JLabel jLabelCalificacion3;
    private javax.swing.JLabel jLabelCalificaciones;
    private javax.swing.JLabel jLabelExamenProm;
    private javax.swing.JLabel jLabelMejor;
    private javax.swing.JLabel jLabelProyectosProm;
    private javax.swing.JLabel jLabelTareasProm;
    private javax.swing.JTextField jTextExamen1;
    private javax.swing.JTextField jTextExamen2;
    private javax.swing.JTextField jTextExamen3;
    private javax.swing.JTextField jTextNombre1;
    private javax.swing.JTextField jTextNombre2;
    private javax.swing.JTextField jTextNombre3;
    private javax.swing.JTextField jTextProyectos1;
    private javax.swing.JTextField jTextProyectos2;
    private javax.swing.JTextField jTextProyectos3;
    private javax.swing.JTextField jTextTareas1;
    private javax.swing.JTextField jTextTareas2;
    private javax.swing.JTextField jTextTareas3;
    // End of variables declaration//GEN-END:variables
}
